version: '3'
services:
    db:
        image: mysql:5.7
        restart: always
        container_name: "mysql"
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=change_this
            - MYSQL_DATABASE=user
            - MYSQL_USER=user
            - MYSQL_PASSWORD=change_this

volumes:
  mysql_data:
    driver: local